import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '../../public/css/globals.css';
import '../../public/css/destino.css';
import '../../public/css/educativa.css';
import '../../public/css/sesion.css';
import '../../public/css/perfil.css';
import '../../public/css/contacto.css';
import '../../public/css/estadisticas.css';
import '../../public/css/resultado.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
